train: True
render_train: False
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay: 10000
gamma: 0.99
batch_size: 32
buffer_size: 10000
learning_rate: 0.0001
target_update_frequency: 2000
start_learning: 1000
model_save_frequency: 300
load_model: False
clip_gradients: True
reward_save_frequency: 30
total_episodes: 5000
train_frequency: 4
model_name: 'DDDQN'
trained_model_folder_and_filename: 'DDDQN-2022-11-30--20-55-08/highway-v0_DuelingDDQNAgent_q_eval_2022-12-01--12-27-39'