train: True
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay: 1000000
gamma: 0.99
batch_size: 128
buffer_size: 100000
learning_rate: 0.001
target_update_frequency: 10000
start_learning: 50000
model_save_frequency: 500
load_model: False
clip_gradients: True
reward_save_frequency: 30
total_episodes: 10000000
train_frequency: 4
model_name: 'DDDQN'
trained_model_path: 'test.pth'