train: True
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay: 1000000
gamma: 0.99
batch_size: 64
buffer_size: 1000000
learning_rate_actor: 0.0001
learning_rate_critic: 0.001
fc1_dims: 400
fc2_dims: 300 
num_frames: 4
tau: 0.001
target_update_frequency: 2500
start_learning: 50
model_save_frequency: 100
load_model: True
clip_gradients: True
reward_save_frequency: 30
train_frequency: 4
model_name: 'DDPG'
trained_model_path: 'test.pth'