
train: True
epsilon_start: 1.0
epsilon_end: 0.05
epsilon_decay: 1000000
gamma: 0.99
batch_size: 32
buffer_size: 10000
learning_rate: 0.001
num_frames: 4
target_update_frequency: 2500
start_learning: 5000
model_save_frequency: 100
load_model: True
clip_gradients: True
reward_save_frequency: 30
train_frequency: 4
csv_file_name: 'rewards_DQN.csv'
model_filename: 'DQN_model'